### ISSUE TITLE
FEATURE(DiseasyActivity$get_scenario_contacts): align function signature of `socialmixr::contact_matrix`

### ISSUE THREAD

**Issue by RasmusSkytte** [ssi-dk/diseasy#69]
This issue tracks a TODO from the `DiseasyActivity$get_scenario_contacts`
```
# TODO: Consider if prop_out is needed
```

That is, we should consider whether to provide the population proportion of the (projected) contact matrix being returned.

This feature request suggest solve this consideration by aligning the function signature of `$get_scenario_contacts()` to that of `socialmixr::contact_matrix`.
Some highlights of the `socialmixr::contact_matrix` function:
1) The output is a named list, with the contact matrix stored in the `$matrix` element and information about participants are stored in `$participants` element
2) It takes a `per.capita = TRUE/FALSE` argument which adds the `$matrix.per.capita` and `$demography` to the output.
   This output is analogous to the output of `$rescale_counts_to_rates()` and has information analagous to the proposed `prop_out`

I suggest we do the following to `DiseasyActivity$get_scenario_contacts`
* [ ] Convert the output to a named list with elements `$matrix` and `$demography`
       `$matrix` would contain the current output and `$demography` would contain the contains of `contact_basis`  aggregated into the
       projected age groups
* [ ] Add a `per_capita = TRUE/FALSE`  argument which adds a `$matrix_per_capita` element to the output.
      This element would be the output of `$rescale_counts_to_rates()`
* [ ] `$rescale_counts_to_rates()` would become a private rather than public funciton
